// Generated by tanstack-db-notion-adapter. Edit the manifest, then regenerate.
import {
  notion,
  notionSchema,
  type InferNotionInput,
  type InferNotionOutput,
} from "tanstack-db-notion-adapter";

export const todoSchema = notionSchema({
  id: notion.id({ name: "Client ID", id: "BBWX" }),
  title: notion.title({ name: "Name", id: "title" }),
  list: notion.select(
    { name: "List", id: "~cCX" },
    ["Inbox", "Anytime", "Someday"] as const,
    "Inbox",
  ),
  scheduledFor: notion.date({ name: "When", id: "atXd" }),
  deadline: notion.date({ name: "Due", id: "xZ%40V" }),
  priority: notion.select(
    { name: "Priority", id: "%5BNmD" },
    ["Low", "Medium", "High"] as const,
    "Medium",
  ),
  position: notion.number({ name: "Position", id: "SeF%5C" }),
  completed: notion.checkbox({ name: "Done", id: "aKwF" }, false),
  completedAt: notion.date({ name: "Completed At", id: "bjxo" }),
  createdAt: notion.createdTime(),
  updatedAt: notion.lastEditedTime(),
  notionPageId: notion.pageId(),
  notionUrl: notion.pageUrl(),
});

export type TodoSchemaInput = InferNotionInput<typeof todoSchema.fields>;

export type TodoSchemaRow = InferNotionOutput<typeof todoSchema.fields>;
