// Generated by tanstack-db-notion-adapter. Edit the manifest, then regenerate.
import { notion, notionSchema, type InferNotionInput, type InferNotionOutput } from "tanstack-db-notion-adapter"

export const todoSchema = notionSchema({
  id: notion.id({ name: "Client ID", id: "BBWX" }),
  priority: notion.select({ name: "Priority", id: "%5BNmD" }, ["Low", "Medium", "High"] as const, "Medium"),
  completed: notion.checkbox({ name: "Done", id: "aKwF" }, false),
  dueDate: notion.date({ name: "Due", id: "xZ%40V" }),
  title: notion.title({ name: "Name", id: "title" }),
  createdAt: notion.createdTime(),
  updatedAt: notion.lastEditedTime(),
  notionPageId: notion.pageId(),
  notionUrl: notion.pageUrl(),
})

export type TodoSchemaInput = InferNotionInput<
  typeof todoSchema.fields
>

export type TodoSchemaRow = InferNotionOutput<
  typeof todoSchema.fields
>
