// Generated by tanstack-db-notion-adapter. Edit the manifest, then regenerate.
import { notion, notionSchema, type InferNotionInput, type InferNotionOutput } from "tanstack-db-notion-adapter"

export const noteSchema = notionSchema({
  id: notion.id({ name: "Client ID", id: "qAe%5D" }),
  pinned: notion.checkbox({ name: "Pinned", id: "%3A%3FeO" }, false),
  entryDate: notion.date({ name: "Entry date", id: "HZXp" }),
  kind: notion.select({ name: "Kind", id: "%5BR%5C%60" }, ["Note", "Journal"] as const, "Note"),
  title: notion.title({ name: "Name", id: "title" }),
  createdAt: notion.createdTime(),
  updatedAt: notion.lastEditedTime(),
  notionPageId: notion.pageId(),
  notionUrl: notion.pageUrl(),
}, { dataSourceId: "3b2c711c-0ceb-80df-b2f2-000ba7723002" })

export type NoteSchemaInput = InferNotionInput<
  typeof noteSchema.fields
>

export type NoteSchemaRow = InferNotionOutput<
  typeof noteSchema.fields
>
